### PR TITLE
Fix template params to match final C++17 iterator categories

### PR DESCRIPTION
**Pull request by rodgert**
https://wg21.link/n4700 changed most of the parallel algorithms from InputIterator to ForwardIterator requirements. This change renames the template parameters to match this change.

### CODE REVIEW

**Comment by tbbdev** [comment]
Hi, rodgert.
Thank you for your request.
One question regarding the patch.
How important the meta-information in the beginning of files?
(For example, // <algorithm> -*- C++ -*-)

Why it's needed here? Can it be removed?
The reason is that we usually haven't any symbols before "copyright information".

**Comment by rodgert** [comment]
The metadata is there so that emacs knows that <algorithm> <numeric> and <memory> are C++. This is pretty consistent with how these headers are tagged in libstdc++

**Comment by rodgert** [comment]
This PR is now updated to include a merge of your 20180329 changes

**Comment by rodgert** [comment]
I think we can close this PR, and I'll merge the changes when you publish them to the GitHub upstream

**Pull request closed without merging**
